export const uefaTeams = [
    { "id": 0, "name": "Chelsea", "country": "gb-eng", },
    { "id": 1, "name": "Ajax", "country": "de", },
    { "id": 2, "name": "Liverpool", "country": "es", },
    { "id": 3, "name": "Inter Miami", "country": "fr", },
    { "id": 4, "name": "Al Nassr", "country": "gb-eng", },
    { "id": 5, "name": "Milan", "country": "it", }, 
    { "id": 6, "name": "Porto", "country": "de", },
    { "id": 7, "name": "Arsenal", "country": "de", }, 
    { "id": 8, "name": "FC Barcelona", "country": "es", }, 
    { "id": 9, "name": "Bayer Leverkusen", "country": "de", }, 
    { "id": 10, "name": "Atlético de Madrid", "country": "es", }, 
    { "id": 11, "name": "Atalanta", "country": "it", }, 
    { "id": 12, "name": "Juventus", "country": "it", }, 
    { "id": 13, "name": "SL Benfica", "country": "pt", }, 
    { "id": 14, "name": "Arsenal", "country": "gb-eng", }, 
    { "id": 15, "name": "Club Brugge", "country": "be", }, 
    { "id": 16, "name": "Shakhtar Donetsk", "country": "ua", }, 
    { "id": 17, "name": "AC Milan", "country": "it", }, 
    { "id": 18, "name": "Feyenoord", "country": "nl", }, 
    { "id": 19, "name": "Sporting CP", "country": "pt", }, 
    { "id": 20, "name": "PSV Eindhoven", "country": "nl", }, 
    { "id": 21, "name": "Dinamo Zagreb", "country": "hr", }, 
    { "id": 22, "name": "FC Salzburg", "country": "at", }, 
    { "id": 23, "name": "LOSC Lille", "country": "fr", }, 
    { "id": 24, "name": "Crvena Zvezda", "country": "rs", }, 
    { "id": 25, "name": "Young Boys", "country": "ch", }, 
    { "id": 26, "name": "Celtic", "country": "gb-sct", }, 
    { "id": 27, "name": "Slovan Bratislava", "country": "sk", },
    { "id": 28, "name": "Monaco", "country": "fr", },
    { "id": 29, "name": "Sparta Praha", "country": "cz", },
    { "id": 30, "name": "Aston Villa", "country": "gb-eng", },
    { "id": 31, "name": "Bologna", "country": "it", },
    { "id": 32, "name": "Girona FC", "country": "es", },
    { "id": 33, "name": "Stuttgart", "country": "de", },
    { "id": 34, "name": "Sturm Graz", "country": "at", },
    { "id": 35, "name": "Stade Brestois", "country": "fr", },
    { "id": 36, "name": "AS Roma", "country": "it", }, 
    { "id": 37, "name": "Man United", "country": "gb-eng", }, 
    { "id": 38, "name": "FC Porto", "country": "pt", }, 
    { "id": 39, "name": "Ajax", "country": "nl", }, 
    { "id": 40, "name": "Rangers", "country": "gb-sct", }, 
    { "id": 41, "name": "Eintracht Frankfurt", "country": "de", }, 
    { "id": 42, "name": "Lazio", "country": "it", }, 
    { "id": 43, "name": "Tottenham", "country": "gb-eng", }, 
    { "id": 44, "name": "Slavia Praha", "country": "cz", }, 
    { "id": 45, "name": "Real Sociedad", "country": "es", }, 
    { "id": 46, "name": "AZ Alkmaar", "country": "nl", }, 
    { "id": 47, "name": "Braga", "country": "pt", }, 
    { "id": 48, "name": "Olympiacos", "country": "gr", }, 
    { "id": 49, "name": "Lyon", "country": "fr", }, 
    { "id": 50, "name": "Paok", "country": "gr", }, 
    { "id": 51, "name": "Fenerbahçe", "country": "tr", }, 
    { "id": 52, "name": "Maccabi Tel-Aviv", "country": "il", }, 
    { "id": 53, "name": "Ferencvárosi", "country": "hu", }, 
    { "id": 54, "name": "Qarabağ", "country": "az", }, 
    { "id": 55, "name": "Galatasaray", "country": "tr", }, 
    { "id": 56, "name": "Viktoria Plzeň", "country": "cz", }, 
    { "id": 57, "name": "Bodø/Glimt", "country": "no", }, 
    { "id": 58, "name": "Union Saint-Gilloise", "country": "be", }, 
    { "id": 59, "name": "Dynamo Kyiv", "country": "ua", }, 
    { "id": 60, "name": "Ludogorets", "country": "bg", }, 
    { "id": 61, "name": "Midtjylland", "country": "dk", }, 
    { "id": 62, "name": "Malmö", "country": "se", }, 
    { "id": 63, "name": "Athletic Club", "country": "es", }, 
    { "id": 64, "name": "Hoffenheim", "country": "de", }, 
    { "id": 65, "name": "Nice", "country": "fr", }, 
    { "id": 66, "name": "Anderlecht", "country": "be", }, 
    { "id": 67, "name": "Twente", "country": "nl", }, 
    { "id": 68, "name": "Beşiktaş", "country": "tr", }, 
    { "id": 69, "name": "FCSB", "country": "ro", }, 
    { "id": 70, "name": "FC RFS", "country": "lv", }, 
    { "id": 71, "name": "Elfsborg", "country": "se", }, 
    { "id": 72, "name": "Sevilla", "country": "es", }, 
    { "id": 73, "name": "Napoli", "country": "it", }, 
    { "id": 74, "name": "København", "country": "dk", }, 
    { "id": 75, "name": "New Castle", "country": "gb-eng", }, 
    { "id": 76, "name": "Union Berlin", "country": "de", }, 
    { "id": 77, "name": "Antwerp", "country": "be", }, 
    { "id": 78, "name": "Lens", "country": "fr", }, 
    { "id": 79, "name": "Chelsea", "country": "gb-eng", },
]

export const conmebolTeams = [
    { "id": "0-conmebol", "name": "Palmeiras", "country": "br", },
    { "id": "1-conmebol", "name": "Flamengo", "country": "br", },
    { "id": "2-conmebol", "name": "Fluminense", "country": "br", },
    { "id": "3-conmebol", "name": "River Plate", "country": "ar", },
    { "id": "4-conmebol", "name": "Boca Juniors", "country": "ar", },
    { "id": "5-conmebol", "name": "Botafogo", "country": "br", },
]

export const afcTeams = [
    { "id": "0-afc", "name": "Al-Hilal", "country": "sa", },
    { "id": "1-afc", "name": "Urawa Reds", "country": "jp", },
    { "id": "2-afc", "name": "Al Ain", "country": "ae", },
    { "id": "3-afc", "name": "Ulsan HD", "country": "kr", },
]

export const cafTeams = [
    { "id": "0-caf", "name": "Al-Ahly", "country": "eg", },
    { "id": "1-caf", "name": "Wydad AC", "country": "ma", },
    { "id": "2-caf", "name": "Espérance de Tunis", "country": "tn", },
    { "id": "3-caf", "name": "Mamelodi Sundowns", "country": "za", },
]

export const concacafTeams = [
    { "id": "0-concacaf", "name": "Monterrey", "country": "mx", },
    { "id": "1-concacaf", "name": "Seattle Sounders", "country": "us", },
    { "id": "2-concacaf", "name": "León", "country": "mx", },
    { "id": "3-concacaf", "name": "Pachuca", "country": "mx", },
    { "id": "4-concacaf", "name": "Inter Miami", "country": "us", },
]

export const ofcTeams = [
    { "id": "0-ofc", "name": "Auckland City", "country": "nz", },
]
